import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link';
import '@fortawesome/fontawesome-free/css/all.min.css';
import Sidebar from './sidebar/Sidebar';
import Header from './header/Header';
import StoreProvider from './context/store';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return<>
  <html lang="en">
      <body className=' bg-[#EEF0FA]'>
        <StoreProvider>
        <div>
          <div className=' grid grid-cols-12 '> 
          <div className=' col-span-2'>
          <Sidebar />
          </div>
          <div className=' col-span-10 '>
            <Header />
            <div className=' mx-[19px] my-[28px]'>
            {children}
            </div>
          
          </div>
          </div>
        </div>
        </StoreProvider>
        </body>
    </html>
  
  </>
    
  
}
